kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-master-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: pure-file
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 17Gi
